<a href="https://colab.research.google.com/github/gurwoghd/2023_WFK_ICT-Laos-/blob/main/sourcecodes/python_libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# FILE HANDLING

In [ ]:
file_path = '/content/drive/MyDrive/Jordan_edu/hello.txt' # cf) file_path can be varied.
# you have to find the path to the file in your drive or computer.

f=open(file_path, 'r')

In [ ]:
f.close()

In [ ]:
with open(file_path, 'w') as f:
  f.write('hello\n')
  f.writelines(['a','b','k']) # abk

In [ ]:
f = open(file_path, 'r')

In [ ]:
str1=f.read(3)
str1

'hel'

In [ ]:
f.tell()

3

In [ ]:
str2 = f.readline()
str2

'lo\n'

In [ ]:
f.tell()

6

In [ ]:
f.seek(0)

0

In [ ]:
f.readlines()

['hello\n', 'abk']

In [ ]:
f.tell()

9

In [ ]:
f.close()

# USING LIABRARY

## math module

### first way to import math module

In [ ]:
import math
math.pow(2,4)

16.0

In [ ]:
math.sqrt(5)

2.23606797749979

### second way to import math module

In [ ]:
import math as m

In [ ]:
m.pow(2,4)

16.0

In [ ]:
m.sqrt(5)

2.23606797749979

### third way to import math module

In [ ]:
from math import pow, sqrt

In [ ]:
pow(2,4)

16.0

In [ ]:
sqrt(5)

2.23606797749979

### forth way to import math module

In [ ]:
from math import pow as p, sqrt as s

In [ ]:
p(2,4)

16.0

In [ ]:
s(5)

2.23606797749979

### Lab
try printing square root of input data (data type is int)

In [ ]:
import math

a = int(input())
print('The square root of', a, 'is',math.sqrt(a))

14
The square root of 14 is 3.7416573867739413


## random module

In [ ]:
import random

In [ ]:
random.random() # this returns float between 0 and 1

0.5226425055368724

In [ ]:
random.uniform(2,4)

3.847501484263841

In [ ]:
random.randint(2,4)

4

In [ ]:
random.randrange(1,7,1)

2

In [ ]:
seq = [1,2,3,4,5,6]
random.choice(seq)

1

In [ ]:
random.shuffle(seq)
seq

[4, 2, 5, 3, 6, 1]

### rock scissors paper

In [ ]:
import random

rsp = ['rock', 'scissors', 'paper']

while True:
  data = int(input("rock scissors paper!! (1: rock, 2: scissor, 3:paper) => "))

  com_data = random.randint(1,3)
  if data == 1 and com_data == 2:
    print('you win!! you: ', rsp[data-1], 'com: ', rsp[com_data-1])
    break
  elif data == 2 and com_data == 3:
    print('you win!! you: ', rsp[data-1], 'com: ', rsp[com_data-1])
    break
  elif data == 3 and com_data == 1:
    print('you win!! you: ', rsp[data-1], 'com: ', rsp[com_data-1])
    break
  else:
    print('you: ', rsp[data-1], 'com: ', rsp[com_data-1])


rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 1
you:  rock com:  rock
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 2
you:  scissors com:  rock
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 3
you:  paper com:  paper
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 3
you:  paper com:  paper
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 3
you:  paper com:  paper
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 3
you:  paper com:  paper
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 3
you:  paper com:  paper
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 3
you:  paper com:  scissors
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 3
you win!! you:  paper com:  rock


### Lab
making a lottery machine

In [ ]:
import math
import random

In [ ]:
money = 10000
cost = 1000
again = 1

answer = []

while again and (money >= cost):
  money -= cost
  for i in range(7):
    answer.append(random.randint(1,11))
  user_ball = map(int, input('input your guess =>').split())
  if user_ball == answer:
    print('you won!!!')
  else:
    print('The answer was', answer)
    print('Do you want to do it again?(cost:1000, remaining money: {})\n'.format(money))
    again = int(input('(1: yes, 0: no) => '))

print('remaining money:', money)


input your guess =>1 2 3 4 5 6 7
The answer was [7, 2, 1, 11, 8, 7, 6]
Do you want to do it again?(cost:1000, remaining money: 9000)

(1: yes, 0: no) => 0
remaining money: 9000


# numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a[0,0]

0

In [ ]:
a[0,:]

array([0, 1, 2])

In [ ]:
a[0,0:2]

array([0, 1])

In [ ]:
b=np.array([0,1,2]) * 10
b

array([ 0, 10, 20])

In [ ]:
idx1 = np.array([True, False, True])

In [ ]:
print(b[idx1])

[ 0 20]


In [ ]:
c=np.array([0,1,2,3,4,5,6,7]) * 10
idx2 = np.array([0,2,3,3,6])
print(c[idx2])

[ 0 20 30 30 60]


In [ ]:
a = a.reshape(3,2)


In [ ]:
d=np.array([[1,2],[3,4],[5,6]])
a_Y = np.concatenate((a,d), axis = 0) # merging vertically
a_Y

array([[0, 1],
       [2, 3],
       [4, 5],
       [1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a_X = np.concatenate((a,d), axis = 1)
a_X

array([[0, 1, 1, 2],
       [2, 3, 3, 4],
       [4, 5, 5, 6]])

In [ ]:

# numpy.split()

e = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [ ]:
e

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
slice_Y_equal_size = np.split(e, 2, axis = 0)
print(slice_Y_equal_size)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [ ]:
slice_Y_different_size = np.split(e, [2,3], axis = 0)
slice_Y_different_size

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

In [ ]:
# numpy.sum()

f = np.arange(4*2*4).reshape(4,2,4)

In [ ]:
new_f = np.sum(f)
new_f

496

In [ ]:
np.sum(f[f>10])

441

In [ ]:
np.max(a)

5

In [ ]:
np.min(a)

0

In [ ]:
np.mean(a)

2.5

In [ ]:
np.std(a)

1.707825127659933

## Lab
use numpy.dot()

In [ ]:
A = np.array([1,2,3,4,5,6])
B = np.array([11,12,13,14,15,16])

In [ ]:
A_reshaped = A.reshape(3,2)
B_reshaped = B.reshape(2,3)

In [ ]:
np.dot(A_reshaped, B_reshaped)

array([[ 39,  42,  45],
       [ 89,  96, 103],
       [139, 150, 161]])

## Lab
use numpy methods

In [ ]:
import numpy as np

A = np.array([[1,4,5,8],[2,1,7,3],[5,4,5,9]])
B=A.reshape(6,2)
Bsplit = np.split(B, 2, axis=0)
C = Bsplit[0]
D = Bsplit[1]
E = np.concatenate((C,D), axis=1)

In [ ]:
numbers = [1,2,3,4,5] # declaring a list

In [ ]:
numbers[0] # to get a value in a list, we use index. And the way getting a value in a list is called "indexing"

1

In [ ]:
numbers[100] # because there is no value in the index 100, an error occurs.

IndexError: ignored

In [ ]:
print("the number of elements in the list numbers: ", len(numbers)) # to get the number of elements in a list, we use len() function

the number of elements in the list numbers:  5


In [ ]:
numbers

[1, 2, 3, 4, 5]

In [ ]:
numbers[0:2] # start: 0 , end: 2, step: 1(default) -> 0~1

[1, 2]

In [ ]:
numbers[0::3] # start: 0, end: len(numbers), step: 3 -> 0,3

[1, 4]

In [ ]:
numbers[::-1] # to reverse a list, we write like this format: name_of_list[::-1]

[5, 4, 3, 2, 1]

In [ ]:
hong = "hello" # strings can be viewed as a list.

In [ ]:
hong[0] # we can do "indexing"

'h'

In [ ]:
hong[0:3] # also we can do "slicing"

'hel'

In [ ]:
s = input()

level


In [ ]:
s_new = s[::-1]

In [ ]:
s_new

'level'

In [ ]:
if s == s_new:
  print("yes")
else:
  print("No")

yes


In [ ]:
s = input() # receiving user data
s_new = s[::-1] # reverse the user data
if s == s_new: # if original data and reversed data are same
  print("yes, it's a palindrome")
else: # if not
  print("No, it's not a palindrome")

In [ ]:
s = [1,2,3,4] # declaring a list

In [ ]:
s[0] = 3 # changing the value at index 0

In [ ]:
s

[3, 2, 3, 4]

In [ ]:
s[3] = 100000 # changing the value at index 3

In [ ]:
s

[3, 2, 3, 100000]

In [ ]:
s.append(900) # adding new element at the end of the list s

In [ ]:
s

[3, 2, 3, 100000, 900]

In [ ]:
s.remove(900) # removing an element from the list. the format is: name_of_list.remove(value)

In [ ]:
s

[3, 2, 3, 100000]

In [ ]:
s.pop(0) # removing an element rom the list. the format is: name_of_list.pop(index)

3

In [ ]:
s

[2, 3, 100000]

In [ ]:
import numpy as np # importing numpy library into a python file and giving a nickname which is "np"

In [ ]:
a = np.array([1,2,3,4,5,6]) # making an ndarray. And this is a 1 dimensional array.
# [1,2,3,4,5,6]

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a[0] # indexing

1

In [ ]:
a[3] # indexing

4

In [ ]:
a[4] # indexing

In [ ]:
a = np.array([[0,1,2], [3,4,5]]) # declaring an ndarray

In [ ]:
a # this is 2 dimensional matrix

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a[0,1] # printing the value at row 0 and column 1

1

In [ ]:
a[1,0] # printing the value at row 1 and column 0

3

In [ ]:
a[0] # printing values at row 0

array([0, 1, 2])

In [ ]:
a[1] # printing values at row 1

array([3, 4, 5])

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a[0, 0:2] # we can do slicing as well

array([0, 1])

In [ ]:
b = a.reshape(3,2) # reshaping ndarray a which is a 2 by 3 matrix into a 3 by 2 matrix. And store the reshaped matrix to variable b

In [ ]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a+10 # +10 operation is applied to all elements in the ndarray a

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
a*10 # *10 operation is applied to all element in the ndarray a

# so this is called "broadcasting", because same operation is applied to all element in an ndarray.

array([[ 0, 10, 20],
       [30, 40, 50]])

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.sum() # you can calculate sum of all elements by using sum() function

15

In [ ]:
a.max() # you can get maximum element in an ndarray by using max() function

5

In [ ]:
a.min() # you can get minimum element in an ndarray by using min() function

0

In [ ]:
a.mean() # you can calculate average of element in an ndarray by using mean() function

2.5

# Lab

y = np.array([220,250,230])

add 100 to each element in y by using broadcasting<br>
print elements whose values are more than 320

In [ ]:
import numpy as np

In [ ]:
y = np.array([220, 250, 230]) # declaring an ndarray

In [ ]:
y

array([220, 250, 230])

In [ ]:
y = y+100 # broadcasting

In [ ]:
y

array([320, 350, 330])

In [ ]:
print(y[y>320])

[350 330]
